### PR TITLE
Built and tested the ADURL module by building from GraphicsMagick sou…

### PR DESCRIPTION
**Pull request by pheest**
…rces.

Outstanding issue: The IOC fails on the Linux /x64 platform with a core dump.
This error appears to be due to a buffer overrun (or similar) error in the internally included xml2 sources.

When tested with Ubuntu installed xml2 version 2.9.1, the IOC worked normally.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
erhmm... Apologies @MarkRivers @pheest but this commit+PR+merge worries me a little bit for a number of reasons: 

* There are 2229 files changed which is presumably a new version of graphicsMagic - but that is not what the commit message indicate. With this large changeset in a single commit it is very difficult to review what exactly it includes and why.
* The commit touches on files in nexussrc, hdf5src  and xml2src - but again the commit message only mention ADURL. The history of the nexus/hdf5/xml2 will now forever have a commit which confusingly refers only to the ADURL driver...
* The PR was closed and then re-opened and merged but without a discussion associated I'm wondering if this could have been accidental?

If graphicsMagick needs an update then I'd suggest a single commit for that update - followed by a series of commits for individual tweaks/changes required to make this work - and then all commits bundled together in one PR.

Please, can we consider reverting and re-doing? 

I hope I'm not being too pedantic here - but I'm genuinely confused and a bit troubled by this one!

**Comment by ulrikpedersen** [comment]
> * The PR was closed and then re-opened and merged but without a discussion associated I'm wondering if this could have been accidental?

Update: I've just noticed #7 and see there **was** a discussion about closing/re-opening the PR (although the PR id was not referenced directly).

**Comment by pheest** [comment]
Hi Ulrik,
This is indeed GraphicksMagick and integration/testing of the ADURL module.
I had a spot of finger trouble, when making the pull request.

I'm sorry if haven't worked through this process as well as you would like.
It is the first time I've done this...

**Comment by MarkRivers** [comment]
This is not an update to GraphicsMagick, becuase GraphicsMagick has never been included in ADSupport previously.  It is a completely new directory that adds GraphicsMagick to ADSupport.  Most of the other files that were changed in NexusSrc, hdf5Src, and xml2src were just line endings changes.  I have undone most of those changes already, so that the next release of ADSupport will look the same as the current release for these files.  These changes to other files were hard to spot because as you said there were so many new files, but that was unavoidable since it is a major new package.

**Comment by ulrikpedersen** [comment]
OK, I see. 

> I'm sorry if haven't worked through this process as well as you would like.
> It is the first time I've done this...

No worries; it does take some getting used to :-) For this particular change I would have made sure that only the new files (graphicsmagick) were staged when making the commit - and make the commit-comment reflect what the change includes, i.e. "adding graphicsmagick sources". If any other tweaks were required to the build system for example, I would add those changes to a subsequent commit with an appropriate comment.

A Pull Request can include many commits - and they can even be changed or more commits added during the review process and it will all be reflected in the history of the repository and the PR.

> Most of the other files that were changed in NexusSrc, hdf5Src, and xml2src were just line endings changes. I have undone most of those changes already, so that the next release of ADSupport will look the same as the current release for these files. 

It is unfortunate side-effect of modern-day editors that automatically change line-endings. Try switching off this feature of your editor if possible and look out for committing files that you don't remember actually making changes in (yes, that can be difficult with such a large change-set).

There is a small downside to 'fixing' the line-endings in a separate commit: the history will be broken by this change where every-line was touched - see for example the 'blame' view on github will not show older history. However, fixing it now would mean re-writing history in the last few commits and would affect everyone with a (recent) clone so its probably not worth the trouble.

**Comment by MarkRivers** [comment]
I undid the changes that @pheest did to xml2Src/dict.c and libxml.h. These files are now back to their original versions from the libxml2 2.9.4 distribution.

- The change he made dict.c (testing if WIN64 is defined) is not needed because WIN64 is never defined.

- The change he made to libxml.h, changing
```#elif defined(_WIN32_WCE) ```
to
``` #elif defined(_WIN32) ```
was being done to avoid errors in nanoftp.c because SEND_ARG2_CAST and GETHOSTBYNAME_ARG_CAST were not defined.  I fixed this problem by adding these (null) definitions to os/WIN32/config.h.  This the correct way to do it, since on WIN32_WCE they were defined in os/WIN32/win32config.h, the file used on that OS.

**Comment by MarkRivers** [comment]
>> You removed envPaths* from this file. This is not correct, envPaths is built by make, and so should not be in git. envPaths.windows and envPaths.linux should be manually copied from envPaths after running make on the appropriate system. This is documented for the simDetector in areaDetector/INSTALL_GUIDE.md.

> Clearly, I had overlooked the relevant section on simDetector. I understand it more clearly now.
My comment is that this isn’t a good process, because it is neither static, nor fully automated.
Would it be possible to improve the build process here, so that the correct files are automatically produced, and not requiring user intervention?

Good comment.  I have improved this so it works "out of the box".  I renamed st.cmd to st_base.cmd, and that is the file that st.cmd.linux and st.cmd.windows now invoke.  I added a new st.cmd. which loads envPaths and then calls st_base.cmd.  So now if the user is doing a typical build they just run st.cmd, but if they want to have both Linux and Windows run from the same directory then they copy envPaths to envPaths.[linux, windows] and invoke st.cmd.[linux, windows].  I renamed st.cmd.win32 to st.cmd.windows and envPaths.win32 to envPaths.windows.  This is now consistent with simDetector.  I will change simDetector to use the same scheme, i.e. it will now work out of the box.

>> 9.	iocs/urlIOC/iocBoot/iocURLDriver/start_epics.bat
You added lines like PATH=%PATH%;..........\ADCore\bin%EPICS_HOST_ARCH%. This is not the correct way to do this. The correct way is to add dllPath.bat as a target in Makefile. Then the EPICS build system will automatically create dllPath.bat which adds the appropriate directories to PATH. I have included your changes to add MAGICK_DEBUG and %EPICS_HOST_ARCH%.

>It would be appropriate to add ‘call dllPath.bat’ to start_epics.bat.

Good point, I have added that.

I have also changed QuantumDepth from 8 to 32 for both Linux and Windows so that we can read any type of image that GraphicsMagick can handle.  The ADURL driver automatically changes the actual data type of the image to match what it really is, i.e. 8-bit RGB if that is what the JPEG file contains, etc.

**Comment by pheest** [comment]
Hi Mark,

Thank you, that’s marvellous.

There’s one more change that I had meant to make (but I wasn’t quite sure how, at the time).

The GraphicsMagick configuration files (delegates.mgk, log.mgk and modules.mgk) should preferably be copied into the executable (Bin) directory.
They have no effect in the directory where they currently reside, but will take effect there.

That would ensure ‘out-of-the-box’ operation, as intended.

Then I think we’re good to go with this...

Cheers,

Peter.

**Comment by MarkRivers** [comment]
> The GraphicsMagick configuration files (delegates.mgk, log.mgk and modules.mgk) should preferably be copied into the executable (Bin) directory.
They have no effect in the directory where they currently reside, but will take effect there.

That does not seem to be true.  I just edited the log.mgk file in the iocURL directory to change this
```  <log events="configure,exception" />```
to this
```  <log events="configure,coder,exception" />```
That had the expected effect, I got lots of debugging output.  So I think GraphicsMagick does read the .mgk files in the current default directory?

**Comment by pheest** [comment]
Oh!

I thought that wasn’t the case.
I think was testing this on Linux – it might be different on Windows.

But if you say it works, all OK...!

Cheers,

Peter.

**Comment by MarkRivers** [comment]
I just tested on both Windows and Linux.  The log.mgk file is definitely found in the iocURLDriver directory on both, because I was able to change the output from stderr to txtfile, and that worked on both OS.  However, on Windows the "log<events ..." line does not seem to be working, because when I add the coder event I don't see that output.  I'm not sure why this would be happening.

**Comment by pheest** [comment]
The config file location behaviour depends on whether useInstalledMagick is defined.

As downloaded from GraphicsMagick, this is defined for Linux, but not for Windows.
I (correctly, I would say) commented it out in magick_config_Linux.h.
This means the current directory is searched for the config files.
Otherwise it will search the installed directory path.

The executable directory is always checked for the config files.

If the environment variables MAGICK_HOME or HOME are defined, the directories specified there are also searched.

I debugged - on Windows - through the log configuration setting. In this order:
a. Initialised (in InitializeLogInfo) to NoEventsMask.
b. Set (by SetLogEventMask) to the value specified by environment variable MAGICK_DEBUG.
c. Added in ReadLogConfigureFile the value(s) from the config file.
d. From InitializeLogInfoPost SetEventLogMask is called a second time and overrides the previously set values with the values from MAGICK_DEBUG.
   This is a bug IMO. I commented out the lines:
    /*
      Set override logging flags using the value of MAGICK_DEBUG if it
      is set in the environment.
    */
//    if ((p=getenv("MAGICK_DEBUG")) != (const char *) NULL)
//      (void) SetLogEventMask(p);
   And it all worked as expected.

**Pull request merged**
