### PR TITLE
Lz4 filter

### PR DESCRIPTION
**Pull request by MarkRivers**
This adds the lz4 filter to the HDF5 library.

I started with https://github.com/nexusformat/HDF5-External-Filter-Plugins/tree/master/LZ4

However, there were a number of issues with that source:
- It did not include a header file, or a filter register function, and so was only usable with run-time loading, not building into HDF5.
- It used malloc() and free() rather than H5_allocate_memory and H5_free_memory.  This caused it to crash with HDF5 1.10.1.
- It was not including arpa/inet.h to define htonl() etc. on Linux

- It was calling LZ4_compress_default as

``` 
compBlockSize = LZ4_compress_default(rpos, roBuf+4,blockSize,nBlocks*4); /// reserve space for compBlockSize
```

The final argument is the size of the output buffer, but it was only passing nBlocks*4 which is only 4 bytes for images under 1 GB.  I don't see how this ever worked.  I changed it to:

```
compBlockSize = LZ4_compress_default(rpos, roBuf+4,blockSize, maxDestSize-outSize); /// reserve space for compBlockSize
```

These are all of my changes:
```
corvette:ADSupport/supportApp/hdf5Src>git diff df099b99cf8513ba6eb1179fc07e1271969beb4a H5Zlz4.c
diff --git a/supportApp/hdf5Src/H5Zlz4.c b/supportApp/hdf5Src/H5Zlz4.c
index 7fb974f..6010ffa 100644
--- a/supportApp/hdf5Src/H5Zlz4.c
+++ b/supportApp/hdf5Src/H5Zlz4.c
@@ -11,9 +11,15 @@
 #include <stdio.h>
 #if defined(_WIN32)
 #include <Winsock2.h>
+#else
+#include <arpa/inet.h>
 #endif
 #include <H5PLextern.h>
 #include <lz4.h>
+#include "lz4_h5filter.h"
+
+#define PUSH_ERR(func, minor, str)                                      \
+    H5Epush1(__FILE__, func, __LINE__, H5E_PLINE, minor, str)

 static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,
         const unsigned int cd_values[], size_t nbytes,
@@ -125,6 +131,7 @@ static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,
         size_t block;
         uint64_t *i64Buf;
         uint32_t *i32Buf;
+        size_t maxDestSize;
         char *rpos;      /* pointer to current read position */
         char *roBuf;    /* pointer to current write position */

@@ -147,8 +154,9 @@ static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,
             blockSize = nbytes;
         }
         nBlocks = (nbytes-1)/blockSize +1;
-        if (NULL==(outBuf = malloc(LZ4_COMPRESSBOUND(nbytes)
-                + 4+8 + nBlocks*4)))
+        maxDestSize = LZ4_compressBound(nbytes) + 4 + 8 + nBlocks*4;
+        outBuf = H5allocate_memory(maxDestSize, false);
+        if (NULL == outBuf)
         {
             goto error;
         }
@@ -174,7 +182,7 @@ static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,
                 blockSize = nbytes - origWritten;

 #if LZ4_VERSION_NUMBER > 10300
-            compBlockSize = LZ4_compress_default(rpos, roBuf+4,blockSize,nBlocks*4); /// reserve space for compBlockSize
+            compBlockSize = LZ4_compress_default(rpos, roBuf+4,blockSize, maxDestSize-outSize); /// reserve space for compBlockSize
 #else
             compBlockSize = LZ4_compress(rpos, roBuf+4, blockSize); /// reserve space for compBlockSize
 #endif
@@ -195,14 +203,14 @@ static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,
             outSize += compBlockSize + 4;
         }

-        free(*buf);
+        H5free_memory(*buf);
         *buf = outBuf;
         *buf_size = outSize;
         outBuf = NULL;
         ret_value = outSize;

     }
-    done:
+    /* done: */
     if(outBuf)
         free(outBuf);
     return ret_value;
@@ -210,7 +218,19 @@ static size_t H5Z_filter_lz4(unsigned int flags, size_t cd_nelmts,

     error:
     if(outBuf)
-        free(outBuf);
+        H5free_memory(outBuf);
     outBuf = NULL;
     return 0;
 }
+
+int lz4_register_h5filter(void){
+
+    int retval;
+
+    retval = H5Zregister(H5Z_LZ4);
+    if(retval<0){
+        PUSH_ERR("lz4_register_h5filter",
+                 H5E_CANTREGISTER, "Can't register lz4 filter");
+    }
+    return retval;
+}
```

### CODE REVIEW

**Comment by MarkRivers** [comment]
@xiaoqiangwang can you take a look at this please?

**Comment by xiaoqiangwang** [comment]
Your change to ``LZ4_compress_default`` looks good to me. For the record, this is the original [PR](https://github.com/nexusformat/HDF5-External-Filter-Plugins/pull/7) adding ``LZ4_compress_default``.

I have successfully tested lz4 filter on Windows and macOS. Also it works with lz4 compressed NDArray from a Codec plugin.

**Comment by MarkRivers** [comment]
@xiaoqiangwang did you read the resulting lz4 compressed HDF5 files OK?  Did both the ones compressed by the plugin and the ones compressed by NDPluginCodec work?  It seems to me that they should be different because H5Zlz4.c adds some additional header information before the compressed data?

How do you configure h5dump to read the compressed files?  Have you built dynamic libraries to do that?

**Comment by xiaoqiangwang** [comment]
I did not try to read back the hdf5 file. Now I did with this package https://pypi.org/project/hdf5plugin. 

Files saved using HDF5 filter can be read back. But files with pre-compressed NDArrays can not. It complains ``OSError: Can't read data (can't locate ID)``. Like you have suspected, some information is missing from saving the pre-compressed NDArrays.

This is true for bs/lz4 and lz4 codec. I have yet to find a setup for blosc codec.

**Comment by xiaoqiangwang** [comment]
For blosc codec, I used this package for read back, https://anaconda.org/conda-forge/blosc-hdf5-plugin.

Either using HDF5 filter or pre-compressed NDArray, the files can be read back.

**Comment by GDYendell** [comment]
It seems that blosc adds the header in its library method (https://github.com/Blosc/c-blosc/blob/f53d9c77bc70f8677ee8f33af197876697b569fa/blosc/blosc.c#L1283), but lz4 does not and has to add it in the hdf5 filter (https://github.com/areaDetector/ADSupport/pull/28/files#diff-1bec0b00cd33804880c95df1ac3757fbR168)

**Comment by MarkRivers** [comment]
I have done quite a bit of work on this.  It now builds dynamically loadable filter plugins for blosc, bitshuffle, and lz4 on both Linux and Windows (and presumably Mac).  I have tested that h5dump on both Linux and Windows can use these libraries to decode files written by NDFileHDF5 with those compressions.

The filters are called HDF5_blosc_plugin.dll, HDF5_bshuf_plugin.dll, and HDF5_lz4_plugin.dll (.so on Linux).

The plugins are built in a new source directory, hdfPluginSrc.  This was simpler in terms of DLL import/export and in terms of parallel make dependencies.

I simplified the blosc_plugin.c and .h files a lot.  The files for all 3 plugins now look very similar.

**Comment by GDYendell** [comment]
As this PR has been a bit of a journey, can I suggest it is squashed before merging (when ready) to keep the history tidy? The sum of the commits gives 1112 additions and 665 deletions, but the overall change is only 455 additions and 9 deletions.

**Comment by MarkRivers** [comment]
Here is a status report:
On Windows I can run h5dump on the following types of files using the filter DLL files built in ADSupport and see the data correctly.
- Uncompressed
- Blosc compression done in HDF5 library
- BS/LZ4 compression done in HDF5 library
- LZ4 compression done in HDF5 library
- Blosc compression done in NDPluginCodec, direct chunk write

It cannot read the data for the following:
- BS/LZ4 compression done in NDPluginCodec, direct chunk write
- LZ4 compression done in NDPluginCodec, direct chunk write

I was previously able to do the same thing on Linux.  However now I cannot read any compressed files with Linux.  It does not even seem to be able to successfully load the shareable libraries, because I don't see any of the debugging messages I have added to the plugins, while I do see them on Windows.  I don't know what is wrong.  Yesterday it was flaky, changing a debugging line in the filter made it work and not work.  Perhaps there is an uninitialized variable problem?

I am working on trying to be able to read the BS/LZ4 and LZ4 files written with direct chunk write by adding the required header information in NDFileHDF5Dataset.cpp.  So far it is not working correctly.  I am limited to debugging with Windows because of the problems with Linux described above.

**Comment by MarkRivers** [comment]
> I am working on trying to be able to read the BS/LZ4 and LZ4 files written with direct chunk write by adding the required header information in NDFileHDF5Dataset.cpp. So far it is not working correctly. I am limited to debugging with Windows because of the problems with Linux described above.

This is now working.  I add the required 12-byte header for BS/LZ4 and 16-byte header for LZ4 in  NDFileHDF5Dataset::writeFile().  These are the file sizes for 10000 frames each 1024 x 1024 x 32-bit using LS4 and BSLZ4 using both normal compression in the HDF5 library and using NDPluginCodec and direct chunk write.  
```
-rw-rw-r--   1 epics   domain users  165238156 Apr  5 17:43 test_hdf5_direct_chunk_lz4_1.h5
-rw-rw-r--   1 epics   domain users  165238156 Apr  5 17:44 test_hdf5_normal_lz4_1.h5
-rw-rw-r--   1 epics   domain users  241248156 Apr  5 17:47 test_hdf5_normal_bslz4_1.h5
-rw-rw-r--   1 epics   domain users  241248156 Apr  5 17:49 test_hdf5_direct_chunk_bslz4_1.h5
```
Note that the files would have been 40GB uncompressed, but are only 165MB and 240MB compressed.  The files are exactly the same size with normal and direct chunk write.  

Using the HDF5 library it was saving 450 files/s with LZ4 and 190 files/s with BS/LZ4.  With direct chunk write it was saving at the full rate of the simDetector, 1320 frames/s.  That would be over 5.2GB/s of uncompressed size.

I still need to figure out why the Linux decompression filters are no longer working.

**Comment by MarkRivers** [comment]
I think I may understand the problem with the filters on Linux.  We are putting the code for the compression filters in libhdf5.so so that we don't need to use dynamically loaded filters in NDFileHDF5.  However, if I run a version of h5dump that was not linked with our version of libhdf5.so then it won't have that filter code.  When the filter plugin attempts to find the symbol H5Z_LZ4 or bshuf_H5Filter they won't be found because it is looking in some other version of libhdf5.so, not our version.  It works on Windows but perhaps the rules for what dll is searched are different on Windows and Linux: on Windows perhaps it uses the version of hdf5.dll that the plugin shareable library was built with, rather than the one that h5dump was built with.

I think we need to put the filters into their own library, not libhdf5.so.  This new library would need to be linked with both from the areaDetector applications and from the plugin libraries.

**Comment by MarkRivers** [comment]
I did a squash merge of the lz4_filter branch into master on my local repository.  Closing this pull request.

**Pull request closed without merging**
